#!/usr/bin/env bash
# Leica — OP Stack L2 sync node (op-geth + op-node) on Sepolia
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

log() { printf '[leica] %s\n' "$1"; }

# --- prereqs ---
for f in genesis.json rollup.json; do
  if [ ! -f "$f" ]; then
    log "ERROR: $f not found — need L2 deployment artifacts"
    log "  genesis.json + rollup.json are generated by op-deployer after L1 contract deploy"
    exit 1
  fi
done

# --- JWT secret (shared between op-geth and op-node) ---
if [ ! -f jwt.hex ]; then
  log "Generating JWT secret"
  openssl rand -hex 32 > jwt.hex
fi

# --- P2P key (optional, for stable peer identity) ---
if [ ! -f p2p-key.txt ]; then
  log "Generating P2P key"
  openssl rand -hex 32 > p2p-key.txt
fi

# --- init op-geth ---
if [ ! -d data/geth/chaindata ]; then
  log "Initializing op-geth with genesis.json"
  mkdir -p data/geth
  docker run --rm \
    -v "$DIR/genesis.json":/genesis.json \
    -v "$DIR/data/geth":/data \
    us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101411.1 \
    geth init --datadir=/data /genesis.json
fi

# --- start stack ---
log "Starting OP Stack: op-geth + op-node"
log "  L1 (Sepolia): https://ethereum-sepolia-rpc.publicnode.com"
log "  L2 RPC: http://localhost:8545"
log "  op-node RPC: http://localhost:9545"
docker compose up -d

log "Stack running — verify:"
log "  curl -s localhost:8545 -XPOST -H 'content-type:application/json' --data '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"eth_blockNumber\",\"params\":[]}'"
log "  curl -s localhost:9545 -XPOST -H 'content-type:application/json' --data '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"optimism_syncStatus\",\"params\":[]}'"

docker compose logs -f
